apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  type: LoadBalancer
  ports:
  - port: 5050
    targetPort: 5050
    protocol: TCP
    name: http
  selector:
    app: wordpress
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: service-wordpress
        ports:
        - containerPort: 5050
          hostPort: 5050
        imagePullPolicy: Never
        env:
          - name: DB_NAME
            value: wordpress
          - name: DB_USER
            value: wp_admin
          - name: DB_PASSWORD
            value: admin
          - name: DB_HOST
            value: mysql
